# Site settings
title: "Lucky Shane"
#email: jacob@jacobtomlinson.co.uk
description: "Lucky Shane"
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "Website for Lucky Shane in progress"
title_image: Images/logo.png

# Social usernames/URLs
instagram_username: luckyshanehairlb
facebook_link: https://www.facebook.com/Lucky-Shane-Hair-Lounge-195744061590/

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
